export const APP_ROUTES = {
  home: "/",
  peach: "/peach",
  orderSystem: "/order-system",
  orderQuery: "/order",
  manage: "/manage",
  tools: "/tools",
  toolOrderSearch: "/tools/order-search",
  toolOrderDetail: "/tools/order",
  toolOrderLink: "/tools/order-link",
  toolPlaceOrder: "/tools/place-order",
  toolPurchasers: "/tools/purchasers",
  toolStoreQuery: "/tools/store-query",
  toolFreightCalculator: "/tools/freight-calculator",
  toolFreightCompare: "/tools/freight-compare",
  customerLogin: "/customer/login",
  customerRegister: "/customer/register",
  customerReset: "/customer/reset",
  lab: "/lab",
  labVideoExtract: "/lab/video-extract",
  labBeadStudio: "/lab/bead-studio",
  labBeadStudioHtml: "/lab/bead-studio.html",
  beadStudio: "/bead-studio",
  otp: "/otp",
  otpGuide: "/otp/guide",
} as const;

export const LOCAL_ROUTES = [
  APP_ROUTES.home,
  APP_ROUTES.peach,
  APP_ROUTES.orderSystem,
  APP_ROUTES.orderQuery,
  APP_ROUTES.manage,
  APP_ROUTES.tools,
  APP_ROUTES.toolOrderSearch,
  APP_ROUTES.toolOrderDetail,
  APP_ROUTES.toolOrderLink,
  APP_ROUTES.toolPlaceOrder,
  APP_ROUTES.toolPurchasers,
  APP_ROUTES.toolStoreQuery,
  APP_ROUTES.toolFreightCalculator,
  APP_ROUTES.toolFreightCompare,
  APP_ROUTES.customerLogin,
  APP_ROUTES.customerRegister,
  APP_ROUTES.customerReset,
  APP_ROUTES.lab,
  APP_ROUTES.labVideoExtract,
  APP_ROUTES.labBeadStudio,
  APP_ROUTES.labBeadStudioHtml,
  APP_ROUTES.beadStudio,
  APP_ROUTES.otp,
  APP_ROUTES.otpGuide,
];

export const API_PATHS = {
  auth: {
    publicKey: "/auth/public-key",
    login: "/auth/login",
    logout: "/auth/logout",
    getInfo: "/auth/me",
    getRouters: "/auth/routes",
    registerOtp: "/auth/register/otp",
    captchaImage: "/auth/captcha",
    sliderVerify: "/auth/captcha/verify",
    sendEmailCode: "/auth/email/code",
    loginByEmail: "/auth/login/email",
		passkeyLogin: "/auth/passkeys/login",
    resetPasswordByEmail: "/auth/password/reset",
  },
  orders: {
    root: "/orders",
    batches: "/orders/batches",
  },
  billing: {
    bills: "/billing/bills",
  },
  logistics: {
    shipments: "/logistics/shipments",
    quotas: "/logistics/quotas",
  },
  catalog: {
    prices: "/catalog/prices",
    products: "/catalog/products",
  },
  customers: {
    root: "/customers",
    purchasers: "/customers/purchasers",
  },
  content: {
    search: "/content/search",
    shortLinks: "/content/short-links",
  },
  stores: {
    root: "/stores",
  },
  identity: {
    access: "/identity/access",
    departments: "/identity/departments",
    menus: "/identity/menus",
    positions: "/identity/positions",
    roles: "/identity/roles",
    users: "/identity/users",
    userProfile: "/identity/users/profile",
    passkeys: "/identity/passkeys",
  },
  administration: {
    root: "/administration",
    config: "/administration/config",
    dictionaryEntries: "/administration/dictionaries/entries",
    dictionaryTypes: "/administration/dictionaries/types",
    mobileMenu: "/administration/mobile-menu",
    notices: "/administration/notices",
  },
  lab: {
    video: "/lab/video",
  },
  otp: {
    vault: "/otp/vault",
    vaultAccount: "/otp/vault/account",
    share: "/otp/share",
  },
  operations: {
    cache: "/operations/cache",
    jobs: "/operations/jobs",
    jobLogs: "/operations/job-logs",
    loginAudits: "/operations/login-audits",
    onlineUsers: "/operations/online-users",
    auditLogs: "/operations/operation-audits",
    server: "/operations/server",
  },
  development: {
    codegen: "/development/codegen",
    messages: "/development/messages",
  },
} as const;
