export function initBeadStudio() {

const PALETTE=[
['A01','纯白','#FFFFFF'],['A02','奶油白','#F3EEDB'],['A03','浅灰','#D8D8D2'],['A04','中灰','#A7AAA8'],['A05','深灰','#6A6F6D'],['A06','黑色','#242625'],['A07','米黄','#F1DDA7'],['A08','浅黄','#F5D368'],['A09','亮黄','#EDB93D'],['A10','橙黄','#E9A053'],['A11','浅橙','#F0B47F'],['A12','橙色','#DE7E4F'],
['B01','浅粉','#EFC4C9'],['B02','樱粉','#DEA7B4'],['B03','玫粉','#C97992'],['B04','正红','#B95658'],['B05','深红','#914A4E'],['B06','酒红','#6F3E47'],['B07','肉粉','#DDB5A6'],['B08','肤色','#D9A986'],['B09','浅棕','#B98B68'],['B10','棕色','#8A654F'],['B11','深棕','#654A3F'],['B12','咖啡','#493A34'],
['C01','浅紫','#CFC3DC'],['C02','薰衣草','#B4A3CC'],['C03','紫色','#8E79A9'],['C04','深紫','#62567E'],['C05','浅蓝','#B8D6E0'],['C06','天蓝','#8DBCD2'],['C07','蓝色','#668EBA'],['C08','深蓝','#526B94'],['C09','藏蓝','#39465F'],['C10','湖蓝','#75B2B5'],['C11','青色','#74B5A5'],['C12','薄荷','#B7D8C7'],
['D01','浅绿','#C2D6A4'],['D02','草绿','#8FB57B'],['D03','绿色','#638E67'],['D04','深绿','#486C50'],['D05','橄榄绿','#85895E'],['D06','墨绿','#3F5848'],['D07','杏色','#DEC39C'],['D08','卡其','#B8A17C'],['D09','沙棕','#9F825F'],['D10','土黄','#AA874F'],['D11','砖红','#9F6758'],['D12','栗棕','#72544A'],
['E01','雾粉','#D9B4B5'],['E02','豆沙','#B88E91'],['E03','浅杏','#E7D1B4'],['E04','象牙','#E9E5D7'],['E05','鼠尾草','#91AA95'],['E06','雾绿','#BFCDBE'],['E07','灰蓝','#8FA5B4'],['E08','雾蓝','#B3C5CF'],['E09','灰紫','#A79EB8'],['E10','淡紫','#C8C0D5'],['E11','蜜桃','#DFA98E'],['E12','陶土','#B97A64'],
['F01','浅青','#B9D7D4'],['F02','苔绿','#75886B'],['F03','芥末','#B7A15C'],['F04','焦糖','#B08058']
].map(([code,name,hex])=>{const n=parseInt(hex.slice(1),16);return{code,name,hex,r:n>>16,g:n>>8&255,b:n&255}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={step:1,img:null,imgURL:'',fit:'cover',scale:1,ox:0,oy:0,w:64,h:64,colorLimit:24,board:32,ignoreWhite:true,cells:[],used:[],tool:'pan',current:PALETTE[0],cellPx:12,undo:[],redo:[],highlight:null,showColor:true,showCode:true,showCoord:true,boardFilter:null};
const el={file:$('#fileInput'),drop:$('#dropZone'),crop:$('#cropCanvas'),cropBox:$('#cropBox'),preview:$('#previewCanvas'),work:$('#workCanvas'),wrap:$('#canvasWrap'),holder:$('#canvasHolder'),legend:$('#legendGrid'),previewLegend:$('#previewLegend'),colorGrid:$('#colorPickGrid'),boardGrid:$('#boardGrid'),toast:$('#toast')};
function toast(t,d=1700){el.toast.textContent=t;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),d)}
function go(step){state.step=step;$$('.view').forEach(v=>v.classList.toggle('active',+v.dataset.view===step));$$('.step').forEach(b=>{const n=+b.dataset.step;b.classList.toggle('active',n===step);b.classList.toggle('done',n<step)});window.scrollTo({top:0,behavior:'smooth'});if(step===2)drawCrop();if(step===3)generate(true);if(step===4){generate(false);fitCanvas()}}
$$('.step').forEach(b=>b.addEventListener('click',()=>{const n=+b.dataset.step;if(n===1||state.img)go(n);else toast('请先上传图片，再进入后续步骤')}));
function loadFile(file){if(!file||!file.type.startsWith('image/'))return;const rd=new FileReader();rd.onload=e=>{const im=new Image();im.onload=()=>{state.img=im;state.imgURL=e.target.result;state.scale=1;state.ox=0;state.oy=0;$('#scaleRange').value=100;$('#xRange').value=0;$('#yRange').value=0;go(2)};im.src=e.target.result};rd.readAsDataURL(file)}
el.file.addEventListener('change',e=>loadFile(e.target.files[0]));['dragenter','dragover'].forEach(t=>el.drop.addEventListener(t,e=>{e.preventDefault();el.drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>el.drop.addEventListener(t,e=>{e.preventDefault();el.drop.classList.remove('drag')}));el.drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
$('#backUpload').onclick=()=>go(1);$('#backCrop').onclick=()=>go(2);$('#toPixelBtn').onclick=()=>go(3);$('#toWorkBtn').onclick=()=>go(4);$('#newBtn').onclick=()=>location.reload();
$$('#fitSeg button').forEach(b=>b.onclick=()=>{$$('#fitSeg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.fit=b.dataset.fit;drawCrop()});
$('#scaleRange').oninput=e=>{state.scale=+e.target.value/100;$('#scaleVal').textContent=e.target.value+'%';drawCrop()};$('#xRange').oninput=e=>{state.ox=+e.target.value/100;$('#xVal').textContent=e.target.value;drawCrop()};$('#yRange').oninput=e=>{state.oy=+e.target.value/100;$('#yVal').textContent=e.target.value;drawCrop()};$('#centerBtn').onclick=()=>{state.scale=1;state.ox=state.oy=0;$('#scaleRange').value=100;$('#xRange').value=$('#yRange').value=0;$('#scaleVal').textContent='100%';$('#xVal').textContent=$('#yVal').textContent='0';drawCrop()};
function drawImageTo(ctx,W,H){ctx.clearRect(0,0,W,H);ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);const iw=state.img.naturalWidth,ih=state.img.naturalHeight;if(state.fit==='stretch'){const dw=W*state.scale,dh=H*state.scale;ctx.drawImage(state.img,(W-dw)/2+state.ox*W/2,(H-dh)/2+state.oy*H/2,dw,dh);return}const base=state.fit==='cover'?Math.max(W/iw,H/ih):Math.min(W/iw,H/ih);const s=base*state.scale,dw=iw*s,dh=ih*s;ctx.drawImage(state.img,(W-dw)/2+state.ox*W/2,(H-dh)/2+state.oy*H/2,dw,dh)}
function drawCrop(){if(!state.img)return;const rect=el.cropBox.getBoundingClientRect(),W=Math.max(280,Math.floor(rect.width-30)),H=Math.max(280,Math.min(620,Math.floor(innerHeight*.62)));const ratio=state.w/state.h;let cw=W,ch=W/ratio;if(ch>H){ch=H;cw=H*ratio}const dpr=Math.min(devicePixelRatio||1,2);el.crop.width=cw*dpr;el.crop.height=ch*dpr;el.crop.style.width=cw+'px';el.crop.style.height=ch+'px';const c=el.crop.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);drawImageTo(c,cw,ch)}
let drag=null;el.crop.addEventListener('pointerdown',e=>{if(!state.img)return;drag={x:e.clientX,y:e.clientY,ox:state.ox,oy:state.oy};el.crop.setPointerCapture(e.pointerId)});el.crop.addEventListener('pointermove',e=>{if(!drag)return;const r=el.crop.getBoundingClientRect();state.ox=Math.max(-1,Math.min(1,drag.ox+(e.clientX-drag.x)/(r.width/2)));state.oy=Math.max(-1,Math.min(1,drag.oy+(e.clientY-drag.y)/(r.height/2)));$('#xRange').value=Math.round(state.ox*100);$('#yRange').value=Math.round(state.oy*100);$('#xVal').textContent=Math.round(state.ox*100);$('#yVal').textContent=Math.round(state.oy*100);drawCrop()});['pointerup','pointercancel'].forEach(t=>el.crop.addEventListener(t,()=>drag=null));el.crop.ondblclick=()=>$('#centerBtn').click();
$$('.size-card').forEach(b=>b.onclick=()=>{const n=+b.dataset.size;state.w=state.h=n;$('#gridW').value=$('#gridH').value=n;$$('.size-card').forEach(x=>x.classList.toggle('active',x===b));generate(true)});['#gridW','#gridH'].forEach(id=>$(id).addEventListener('change',()=>{state.w=Math.max(8,Math.min(160,+$('#gridW').value||64));state.h=Math.max(8,Math.min(160,+$('#gridH').value||64));$$('.size-card').forEach(x=>x.classList.toggle('active',+x.dataset.size===state.w&&state.w===state.h));generate(true)}));
const limits=[12,24,36,64],labels=['精简 · 12 色','推荐 · 24 色','精细 · 36 色','原色 · 64 色'];$('#colorRange').oninput=e=>{state.colorLimit=limits[+e.target.value];$('#colorLabel').textContent=labels[+e.target.value];generate(true)};$('#boardSize').onchange=e=>{state.board=+e.target.value;generate(true)};$('#ignoreWhite').onchange=e=>{state.ignoreWhite=e.target.checked;generate(true)};
function srgbToLinear(v){v/=255;return v<=0.04045?v/12.92:Math.pow((v+0.055)/1.055,2.4)}
function rgbToLab(r,g,b){const rl=srgbToLinear(r),gl=srgbToLinear(g),bl=srgbToLinear(b);let x=rl*0.4124564+gl*0.3575761+bl*0.1804375,y=rl*0.2126729+gl*0.7151522+bl*0.0721750,z=rl*0.0193339+gl*0.1191920+bl*0.9503041;x/=0.95047;y/=1;z/=1.08883;const f=t=>t>0.008856?Math.cbrt(t):(7.787*t+16/116);const fx=f(x),fy=f(y),fz=f(z);return{L:116*fy-16,a:500*(fx-fy),b:200*(fy-fz)}}
function labDist(a,b){const dL=a.L-b.L,da=a.a-b.a,db=a.b-b.b;return dL*dL+da*da+db*db}
function saturation(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b);return max?((max-min)/max):0}
PALETTE.forEach(p=>{if(!p.lab)p.lab=rgbToLab(p.r,p.g,p.b)})
function nearestLab(cell,pal){let best=pal[0],bestD=1e20;for(const p of pal){const d=labDist(cell.lab,p.lab);if(d<bestD){bestD=d;best=p}}return best}
function sampleCells(w,h,s=6){const c=document.createElement('canvas');c.width=w*s;c.height=h*s;const x=c.getContext('2d',{willReadFrequently:true});drawImageTo(x,w*s,h*s);const data=x.getImageData(0,0,w*s,h*s).data,raw=[];const center=(s-1)/2;for(let gy=0;gy<h;gy++)for(let gx=0;gx<w;gx++){
  let sr=0,sg=0,sb=0,sw=0,centerR=0,centerG=0,centerB=0,centerW=0;
  const votes=new Map(), samples=[];
  for(let yy=0;yy<s;yy++)for(let xx=0;xx<s;xx++){
    const i=((gy*s+yy)*(w*s)+(gx*s+xx))*4,r=data[i],g=data[i+1],b=data[i+2],a=data[i+3];
    if(a<48)continue; if(state.ignoreWhite&&r>248&&g>248&&b>248)continue;
    const d=Math.hypot(xx-center,yy-center);
    const w1=1+Math.max(0,(center*1.2-d))*0.55;
    sr+=r*w1; sg+=g*w1; sb+=b*w1; sw+=w1;
    if(d<=center*0.58){centerR+=r*w1; centerG+=g*w1; centerB+=b*w1; centerW+=w1}
    const lab=rgbToLab(r,g,b); const tmp={lab}; const near=nearestLab(tmp,PALETTE);
    votes.set(near.code,(votes.get(near.code)||0)+w1);
    samples.push({r,g,b,lab,w:w1});
  }
  if(!sw||!samples.length){raw.push(null);continue}
  const meanR=Math.round(sr/sw),meanG=Math.round(sg/sw),meanB=Math.round(sb/sw);
  const centerr=centerW?Math.round(centerR/centerW):meanR, centerg=centerW?Math.round(centerG/centerW):meanG, centerb=centerW?Math.round(centerB/centerW):meanB;
  const meanLab=rgbToLab(meanR,meanG,meanB), centerLab=rgbToLab(centerr,centerg,centerb);
  let dominantCode=null,dominantWeight=0; for(const [code,weight] of votes){ if(weight>dominantWeight){ dominantWeight=weight; dominantCode=code; } }
  let variance=0; for(const sm of samples) variance+=labDist(meanLab,sm.lab)*sm.w; variance/=sw;
  raw.push({r:meanR,g:meanG,b:meanB,lab:meanLab,center:{r:centerr,g:centerg,b:centerb,lab:centerLab},sat:saturation(meanR,meanG,meanB),var:variance,dominantCode,dominantRatio:dominantWeight/sw});
}
return raw}
function kMeansPalette(raw,k){const pts=raw.filter(Boolean); if(!pts.length) return []; k=Math.max(1,Math.min(k,pts.length)); const weighted=pts.map(p=>({lab:p.lab,w:1+p.sat*0.55+Math.min(1.4,p.var/180)*0.3+(p.dominantRatio>0.52?0.18:0)}));
  const centers=[]; centers.push(weighted[Math.floor(Math.random()*weighted.length)].lab);
  while(centers.length<k){ let total=0; const ds=[]; for(const p of weighted){ let best=1e20; for(const c of centers){ const d=labDist(p.lab,c); if(d<best) best=d; } const score=best*p.w; ds.push(score); total+=score; }
    if(!total) break; let pick=Math.random()*total, idx=0; for(let i=0;i<ds.length;i++){ pick-=ds[i]; if(pick<=0){ idx=i; break; } } centers.push(weighted[idx].lab); }
  for(let iter=0;iter<7;iter++){ const buckets=centers.map(()=>({L:0,a:0,b:0,w:0})); for(const p of weighted){ let bi=0,bd=1e20; for(let i=0;i<centers.length;i++){ const d=labDist(p.lab,centers[i]); if(d<bd){bd=d;bi=i;} } buckets[bi].L+=p.lab.L*p.w; buckets[bi].a+=p.lab.a*p.w; buckets[bi].b+=p.lab.b*p.w; buckets[bi].w+=p.w; }
    for(let i=0;i<centers.length;i++){ if(buckets[i].w>0) centers[i]={L:buckets[i].L/buckets[i].w,a:buckets[i].a/buckets[i].w,b:buckets[i].b/buckets[i].w}; }
  }
  return centers; }
function choosePalette(raw){ const target=Math.max(1,state.colorLimit); const centers=kMeansPalette(raw,target); const picked=[]; const usedCodes=new Set();
  for(const c of centers){ let best=null,bd=1e20; for(const p of PALETTE){ const d=labDist(c,p.lab); if(d<bd && !usedCodes.has(p.code)){ bd=d; best=p; } } if(best){ picked.push(best); usedCodes.add(best.code); } }
  const popularity=new Map(); for(const cell of raw){ if(!cell) continue; const p=nearestLab(cell,PALETTE); popularity.set(p.code,(popularity.get(p.code)||0)+1+cell.sat*0.25+(cell.var>90?0.2:0)); if(cell.dominantCode) popularity.set(cell.dominantCode,(popularity.get(cell.dominantCode)||0)+cell.dominantRatio*0.45); }
  const extras=[...popularity.entries()].sort((a,b)=>b[1]-a[1]).map(([code])=>PALETTE.find(p=>p.code===code)).filter(Boolean);
  for(const p of extras){ if(picked.length>=target) break; if(!usedCodes.has(p.code)){ picked.push(p); usedCodes.add(p.code); } }
  const real=raw.filter(Boolean); if(real.length){ const light=real.reduce((a,b)=>a.lab.L>b.lab.L?a:b), dark=real.reduce((a,b)=>a.lab.L<b.lab.L?a:b), sat=real.reduce((a,b)=>a.sat>b.sat?a:b); for(const source of [light,dark,sat]){ const p=nearestLab(source,PALETTE); if(p && !usedCodes.has(p.code) && picked.length<target){ picked.push(p); usedCodes.add(p.code); } } }
  return picked.slice(0,target); }
function assignCellColor(cell,pal){ if(!cell) return null; const meanPick=nearestLab(cell,pal), centerPick=nearestLab(cell.center,pal), domPick=cell.dominantCode ? (pal.find(p=>p.code===cell.dominantCode) || meanPick) : meanPick; const meanD=labDist(cell.lab,meanPick.lab), centerD=labDist(cell.center.lab,centerPick.lab), domD=labDist(cell.lab,domPick.lab); if(cell.var>150 && cell.dominantRatio>0.44 && domD<=meanD*1.28) return domPick; if(centerPick.code!==meanPick.code && centerD<meanD*0.9) return centerPick; return meanPick; }
function cleanupCells(cells,w,h,raw){const out=cells.slice(),dirs=[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[1,-1],[-1,1],[1,1]];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,p=cells[i],meta=raw[i];if(!p||!meta)continue;if(meta.var>120||meta.dominantRatio>0.5)continue;const around=new Map();for(const [dx,dy] of dirs){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const q=cells[ny*w+nx];if(q)around.set(q.code,(around.get(q.code)||0)+1)}const same=around.get(p.code)||0;let winner=null,max=0;for(const [code,count] of around){if(count>max){max=count;winner=code}}if(same<=1&&winner&&winner!==p.code&&max>=6){out[i]=PALETTE.find(v=>v.code===winner)||p}}return out}
function generate(previewOnly){if(!state.img)return;const w=state.w,h=state.h,raw=sampleCells(w,h,6);let pal=choosePalette(raw);if(!pal.length)pal=[PALETTE[0]];state.cells=raw.map(v=>assignCellColor(v,pal));state.cells=cleanupCells(state.cells,w,h,raw);recount();renderPreview();if(!previewOnly){state.undo=[];state.redo=[];renderWorkbench();renderColors();renderBoards();renderLegend()}}
function recount(){const m=new Map();state.cells.forEach(p=>{if(p)m.set(p.code,(m.get(p.code)||0)+1)});state.used=PALETTE.filter(p=>m.has(p.code)).map(p=>({...p,count:m.get(p.code)})).sort((a,b)=>b.count-a.count);const beads=state.cells.filter(Boolean).length,boards=state.board?Math.ceil(state.w/state.board)*Math.ceil(state.h/state.board):1;$('#estBeads').textContent=beads.toLocaleString();$('#estColors').textContent=state.used.length+' 色';$('#estBoards').textContent=boards+' 块'}
function renderPreview(){requestAnimationFrame(()=>{const box=el.preview.parentElement,maxW=Math.max(280,box.clientWidth-28),maxH=Math.max(320,box.clientHeight-28),px=Math.max(3,Math.min(14,Math.floor(Math.min(maxW/state.w,maxH/state.h))));drawGrid(el.preview,px,false,false,true)});el.previewLegend.innerHTML=state.used.map(p=>`<div class="mini-color"><i class="dot" style="background:${p.hex}"></i><div><b>${p.code} · ${p.name}</b><br><span>${p.count} 颗</span></div><span>${Math.ceil(p.count*1.08)}</span></div>`).join('')}
function textColor(p){return (p.r*299+p.g*587+p.b*114)/1000>155?'#242424':'#fff'}
function drawGrid(canvas,px,codes=true,coords=true,colors=true,filter=state.boardFilter){const w=state.w,h=state.h,coord=coords?26:0,dpr=Math.min(devicePixelRatio||1,2);let sx=0,sy=0,ew=w,eh=h;if(filter){sx=filter.x;sy=filter.y;ew=filter.w;eh=filter.h}canvas.width=(ew*px+coord)*dpr;canvas.height=(eh*px+coord)*dpr;canvas.style.width=(ew*px+coord)+'px';canvas.style.height=(eh*px+coord)+'px';const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#fff';c.fillRect(0,0,ew*px+coord,eh*px+coord);c.textAlign='center';c.textBaseline='middle';for(let yy=0;yy<eh;yy++)for(let xx=0;xx<ew;xx++){const gx=sx+xx,gy=sy+yy,p=state.cells[gy*w+gx],x=coord+xx*px,y=coord+yy*px;let fill=p&&colors?p.hex:'#fff';if(state.highlight&&p&&p.code!==state.highlight)fill='#f3f2ee';c.fillStyle=fill;c.fillRect(x,y,px,px);if(p&&codes&&px>=15){c.fillStyle=state.highlight&&p.code!==state.highlight?'#bbb':textColor(p);c.font=`600 ${Math.max(6,Math.floor(px*.34))}px Arial`;c.fillText(p.code,x+px/2,y+px/2)}}
for(let x=0;x<=ew;x++){const gx=sx+x,isBoard=state.board&&gx%state.board===0,is5=gx%5===0;c.beginPath();c.strokeStyle=isBoard?'rgba(111,138,158,.95)':is5?'rgba(30,35,31,.54)':'rgba(30,35,31,.16)';c.lineWidth=isBoard?2.2:is5?1.1:.45;c.moveTo(coord+x*px,coord);c.lineTo(coord+x*px,coord+eh*px);c.stroke()}for(let y=0;y<=eh;y++){const gy=sy+y,isBoard=state.board&&gy%state.board===0,is5=gy%5===0;c.beginPath();c.strokeStyle=isBoard?'rgba(111,138,158,.95)':is5?'rgba(30,35,31,.54)':'rgba(30,35,31,.16)';c.lineWidth=isBoard?2.2:is5?1.1:.45;c.moveTo(coord,coord+y*px);c.lineTo(coord+ew*px,coord+y*px);c.stroke()}if(coords){c.fillStyle='#626763';c.font='9px Arial';for(let x=0;x<ew;x++)if(x%5===0||px>=16)c.fillText(String(sx+x+1),coord+x*px+px/2,coord/2);for(let y=0;y<eh;y++)if(y%5===0||px>=16){c.save();c.translate(coord/2,coord+y*px+px/2);c.rotate(-Math.PI/2);c.fillText(String(sy+y+1),0,0);c.restore()}}}
function renderWorkbench(){const beads=state.cells.filter(Boolean).length,boards=state.board?Math.ceil(state.w/state.board)*Math.ceil(state.h/state.board):1;$('#metaSize').textContent=`${state.w}×${state.h}`;$('#metaBeads').textContent=beads.toLocaleString()+' 颗';$('#metaColors').textContent=state.used.length+' 色';$('#metaBoards').textContent=boards+' 板';drawGrid(el.work,state.cellPx,state.showCode,state.showCoord,state.showColor)}
function fitCanvas(){requestAnimationFrame(()=>{const avail=Math.max(260,el.wrap.clientWidth-16),filter=state.boardFilter,ww=filter?filter.w:state.w,coord=state.showCoord?26:0;state.cellPx=Math.max(4,Math.min(18,Math.floor((avail-coord)/ww)));renderWorkbench()})}
$('#fitBtn').onclick=()=>{fitCanvas();toast('已按当前屏幕重新适配图纸')};$('#zoomIn').onclick=()=>{state.cellPx=Math.min(28,state.cellPx+2);renderWorkbench();toast('已放大图纸，方便看细节',900)};$('#zoomOut').onclick=()=>{state.cellPx=Math.max(4,state.cellPx-2);renderWorkbench();toast('已缩小图纸，方便看整体',900)};
function setTool(t){state.tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$$('[data-mobile]').forEach(b=>b.classList.toggle('active',b.dataset.mobile===t));el.holder.classList.toggle('pan',t==='pan');const tips={pan:'已切换到浏览模式：可拖动画布，不会改动图纸',draw:'已切换到画笔模式：点击方格即可上色',erase:'已切换到擦除模式：点击方格可清空为空豆',pick:'已切换到吸色模式：点击图纸中的颜色可快速取色'};if(tips[t])toast(tips[t])}$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>b.dataset.tool&&setTool(b.dataset.tool)));$$('[data-mobile]').forEach(b=>b.onclick=()=>setTool(b.dataset.mobile));
function renderColors(){el.colorGrid.innerHTML=PALETTE.map(p=>`<button class="color-pick ${p.code===state.current.code?'active':''}" data-code="${p.code}" title="${p.code} ${p.name} ${p.hex}"><div class="c" style="background:${p.hex}"></div><small>${p.code}</small></button>`).join('');el.colorGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.current=PALETTE.find(p=>p.code===b.dataset.code);$('#currentColorCode').textContent=state.current.code;renderColors();toast(`当前颜色：${state.current.code} · ${state.current.name}`)})}
function boardData(){if(!state.board)return[{x:0,y:0,w:state.w,h:state.h,label:'全图'}];const out=[];let n=1;for(let y=0;y<state.h;y+=state.board)for(let x=0;x<state.w;x+=state.board)out.push({x,y,w:Math.min(state.board,state.w-x),h:Math.min(state.board,state.h-y),label:`板 ${n++}`});return out}
function renderBoards(){const arr=boardData();el.boardGrid.innerHTML=arr.map((b,i)=>`<button class="board-btn" data-i="${i}" title="查看 ${b.label} 的单独图纸"><b>${b.label}</b><br><span>${b.w}×${b.h} · 第 ${Math.floor(b.y/(state.board||state.h))+1} 行 / ${Math.floor(b.x/(state.board||state.w))+1} 列</span></button>`).join('');el.boardGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>{const d=arr[+b.dataset.i];state.boardFilter=d.label==='全图'?null:d;el.boardGrid.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));fitCanvas();toast(`正在查看 ${d.label}`)})}$('#allBoards').onclick=()=>{state.boardFilter=null;renderBoards();fitCanvas();toast('已切换回整张图纸')};
function renderLegend(){el.legend.innerHTML=state.used.map(p=>`<div class="legend-item ${state.highlight===p.code?'active':''}" data-code="${p.code}" title="点击高亮 ${p.code} 在图纸中的位置"><i class="legend-sw" style="background:${p.hex}"></i><div><b>${p.code} · ${p.name}</b><small>${p.hex}</small></div><strong>${p.count}</strong></div>`).join('');el.legend.querySelectorAll('.legend-item').forEach(i=>i.onclick=()=>{const code=i.dataset.code;const active=state.highlight===code;state.highlight=active?null:code;renderLegend();renderWorkbench();toast(active?`已取消高亮 ${code}`:`已高亮 ${code}，方便核对位置`)})}
function snapshot(){state.undo.push(state.cells.map(p=>p?p.code:null));if(state.undo.length>40)state.undo.shift();state.redo=[]}function restore(arr){state.cells=arr.map(c=>c?PALETTE.find(p=>p.code===c):null);recount();renderWorkbench();renderLegend()}$('#undoBtn').onclick=()=>{if(!state.undo.length){toast('没有可撤销的操作');return}state.redo.push(state.cells.map(p=>p?p.code:null));restore(state.undo.pop());toast('已撤销上一步修改',900)};$('#redoBtn').onclick=()=>{if(!state.redo.length){toast('没有可重做的操作');return}state.undo.push(state.cells.map(p=>p?p.code:null));restore(state.redo.pop());toast('已恢复刚才撤销的修改',900)};
function cellFromEvent(e){const r=el.work.getBoundingClientRect(),coord=state.showCoord?26:0,filter=state.boardFilter,sx=filter?filter.x:0,sy=filter?filter.y:0,x=Math.floor((e.clientX-r.left-coord)/state.cellPx),y=Math.floor((e.clientY-r.top-coord)/state.cellPx),ww=filter?filter.w:state.w,hh=filter?filter.h:state.h;if(x<0||y<0||x>=ww||y>=hh)return null;return{x:sx+x,y:sy+y,i:(sy+y)*state.w+(sx+x)}}let painting=false,changed=false;el.work.addEventListener('pointerdown',e=>{if(state.tool==='pan')return;const c=cellFromEvent(e);if(!c)return;if(state.tool==='pick'){const p=state.cells[c.i];if(p){state.current=p;$('#currentColorCode').textContent=p.code;renderColors();toast(`已吸取 ${p.code} · ${p.name}`)}else{toast('这个位置是空豆，没有可吸取的颜色',1200)}return}snapshot();painting=true;changed=true;el.work.setPointerCapture(e.pointerId);state.cells[c.i]=state.tool==='erase'?null:state.current;recount();renderWorkbench()});el.work.addEventListener('pointermove',e=>{if(!painting)return;const c=cellFromEvent(e);if(!c)return;state.cells[c.i]=state.tool==='erase'?null:state.current;recount();renderWorkbench()});['pointerup','pointercancel'].forEach(t=>el.work.addEventListener(t,()=>{if(changed){renderLegend();changed=false}painting=false}));
$('#showColorBtn').onclick=()=>{state.showColor=!state.showColor;$('#showColorBtn').classList.toggle('active',state.showColor);renderWorkbench();toast(state.showColor?'已显示颜色':'已隐藏颜色')} ;$('#showCodeBtn').onclick=()=>{state.showCode=!state.showCode;$('#showCodeBtn').classList.toggle('active',state.showCode);renderWorkbench();toast(state.showCode?'已显示格内色号':'已隐藏格内色号')} ;$('#showCoordBtn').onclick=()=>{state.showCoord=!state.showCoord;$('#showCoordBtn').classList.toggle('active',state.showCoord);fitCanvas();toast(state.showCoord?'已显示坐标':'已隐藏坐标')} ;
function getExportConfig(level='ultra'){const map={hd:{px:60,label:'高清'},ultra:{px:90,label:'超清'},max:{px:120,label:'极清'}};return map[level]||map.ultra}
function clampExportPx(targetPx,ww,hh,colorCount){let px=targetPx;for(let i=0;i<8;i++){const scale=Math.min(px/30,2),coord=Math.round(34*scale),legendRows=Math.ceil(colorCount/4),legendH=Math.round(80*scale)+legendRows*Math.round(54*scale),W=Math.max(Math.round(ww*px+coord+Math.round(40*scale)*2),Math.round(1100*scale)),H=Math.round(hh*px+coord+legendH+130*scale);if(Math.max(W,H)<=16000 && W*H<=180000000)break;px=Math.max(36,Math.floor(px*0.85));}return px}

function exportPNG(opts={}){const filter=state.boardFilter,ww=filter?filter.w:state.w,hh=filter?filter.h:state.h,cfg=getExportConfig(opts.quality||'ultra'),showCodes=opts.showCodes!==false;let px=clampExportPx(cfg.px,ww,hh,state.used.length);const scale=Math.min(px/30,2),coord=Math.round(34*scale),cols=4,margin=Math.round(40*scale),titleY=Math.round(42*scale),subY=Math.round(67*scale),gridY=Math.round(86*scale),legendRows=Math.ceil(state.used.length/cols),legendRowH=Math.round(54*scale),legendH=Math.round(80*scale)+legendRows*legendRowH,W=Math.max(Math.round(ww*px+coord+margin*2),Math.round(1100*scale)),H=Math.round(hh*px+coord+legendH+130*scale),out=document.createElement('canvas');out.width=W;out.height=H;const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,W,H);c.fillStyle='#282b29';c.font=`700 ${Math.round(28*scale)}px Arial`;c.textAlign='left';c.fillText(`拼豆图纸 ${filter?filter.label+' · ':''}${ww}×${hh}`,margin,titleY);c.fillStyle='#666';c.font=`${Math.round(14*scale)}px Arial`;c.fillText(`${showCodes?'格内色号':'纯色方格'} · 每 5 格粗线 · ${state.used.length} 种颜色 · ${cfg.label}导出`,margin,subY);const temp=document.createElement('canvas');drawGrid(temp,px,showCodes,true,true,filter);const dpr=Math.min(devicePixelRatio||1,2);c.drawImage(temp,margin,gridY,temp.width/dpr,temp.height/dpr);const y0=gridY+hh*px+coord+Math.round(42*scale);c.fillStyle='#282b29';c.font=`700 ${Math.round(20*scale)}px Arial`;c.fillText('颜色图示 · 用量清单',margin,y0);const colW=(W-margin*2)/cols,sw=Math.round(32*scale);state.used.forEach((p,i)=>{const col=i%cols,row=Math.floor(i/cols),x=margin+col*colW,y=y0+Math.round(22*scale)+row*legendRowH;c.fillStyle=p.hex;c.fillRect(x,y,sw,sw);c.strokeStyle='#aaa';c.strokeRect(x,y,sw,sw);c.fillStyle='#282b29';c.font=`700 ${Math.round(13*scale)}px Arial`;c.fillText(`${p.code}  ${p.name}`,x+Math.round(42*scale),y+Math.round(13*scale));c.fillStyle='#777';c.font=`${Math.round(12*scale)}px Arial`;c.fillText(`${p.count} 颗 · 建议备 ${Math.ceil(p.count*1.08)} 颗`,x+Math.round(42*scale),y+Math.round(29*scale))});const a=document.createElement('a');a.download=`拼豆图纸_${cfg.label}_${showCodes?'带色号':'无色号'}_${filter?filter.label+'_':''}${state.w}x${state.h}.png`;a.href=out.toDataURL('image/png');a.click();toast(`已导出${cfg.label} PNG · ${showCodes?'带色号':'无色号'} · ${W}×${H}px${px<cfg.px?'（已自动压缩到浏览器可承受范围）':''}`,2600)}
const exportUI={quality:'ultra',showCodes:true};
function updateExportInfo(){const cfg=getExportConfig(exportUI.quality),filter=state.boardFilter,ww=filter?filter.w:state.w,hh=filter?filter.h:state.h;let px=clampExportPx(cfg.px,ww,hh,state.used.length);const scale=Math.min(px/30,2),coord=Math.round(34*scale),cols=4,margin=Math.round(40*scale),legendRows=Math.ceil(state.used.length/cols),legendH=Math.round(80*scale)+legendRows*Math.round(54*scale),W=Math.max(Math.round(ww*px+coord+margin*2),Math.round(1100*scale)),H=Math.round(hh*px+coord+legendH+130*scale);$('#exportInfo').textContent=`预计导出 ${cfg.label} PNG · ${exportUI.showCodes?'纸张显示格内色号':'纸张不显示格内色号'} · 约 ${W}×${H}px。`+(px<cfg.px?' 当前尺寸较大，系统会自动压缩到稳定范围。':'');}
function openExportModal(){exportUI.quality='ultra';exportUI.showCodes=true;$$('[data-export-quality]').forEach(b=>b.classList.toggle('active',b.dataset.exportQuality==='ultra'));$('#exportShowCodes').checked=true;updateExportInfo();document.body.classList.add('export-open');$('#exportBackdrop').classList.add('open');$('#exportModal').classList.add('open')}
function closeExportModal(){document.body.classList.remove('export-open');$('#exportBackdrop').classList.remove('open');$('#exportModal').classList.remove('open')}
$$('[data-export-quality]').forEach(b=>b.onclick=()=>{exportUI.quality=b.dataset.exportQuality;$$('[data-export-quality]').forEach(x=>x.classList.toggle('active',x===b));updateExportInfo()});$('#exportShowCodes').onchange=e=>{exportUI.showCodes=e.target.checked;updateExportInfo()};$('#cancelExport').onclick=closeExportModal;$('#exportBackdrop').onclick=closeExportModal;$('#confirmExport').onclick=()=>{closeExportModal();exportPNG({quality:exportUI.quality,showCodes:exportUI.showCodes})};$('#exportBtn').onclick=openExportModal;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#exportModal').classList.contains('open'))closeExportModal()});

$('#csvBtn').onclick=()=>{const rows=['色号,颜色名称,HEX,实际数量,建议备豆数量',...state.used.map(p=>`${p.code},${p.name},${p.hex},${p.count},${Math.ceil(p.count*1.08)}`)];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`拼豆用量_${state.w}x${state.h}.csv`;a.click();URL.revokeObjectURL(a.href)};
$('#saveBtn').onclick=()=>{const data={version:1,w:state.w,h:state.h,board:state.board,cells:state.cells.map(p=>p?p.code:null)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download='拼豆工程.json';a.click();URL.revokeObjectURL(a.href);toast('工程已保存，下次可继续编辑')} ;
const backdrop=$('#sheetBackdrop'),sheet=$('#mobileSheet'),sheetTitle=$('#sheetTitle'),sheetContent=$('#sheetContent');function openSheet(type){backdrop.classList.add('open');sheet.classList.add('open');if(type==='colors'){sheetTitle.textContent='颜色';sheetContent.innerHTML='<div class="color-pick-grid">'+PALETTE.map(p=>`<button class="color-pick ${p.code===state.current.code?'active':''}" data-code="${p.code}"><div class="c" style="background:${p.hex}"></div><small>${p.code}</small></button>`).join('')+'</div>';sheetContent.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.current=PALETTE.find(p=>p.code===b.dataset.code);$('#currentColorCode').textContent=state.current.code;renderColors();openSheet('colors')})}else{sheetTitle.textContent='更多';sheetContent.innerHTML=`<div style="display:grid;gap:8px"><button class="btn block" id="mAll">查看全图</button><button class="btn block" id="mFit">适配屏幕</button><button class="btn block" id="mUndo">撤销</button><button class="btn block" id="mRedo">重做</button><button class="btn primary block" id="mExport">导出防错图纸 PNG</button><div class="helper">导出时可选择高清 / 超清 / 极清，并决定纸张是否显示格内色号</div></div><div style="margin-top:12px"><h4 style="margin:0 0 8px;font-size:13px">分板</h4><div class="board-grid">${boardData().map((b,i)=>`<button class="board-btn" data-board="${i}">${b.label}<br><span>${b.w}×${b.h}</span></button>`).join('')}</div></div>`;$('#mAll').onclick=()=>{state.boardFilter=null;fitCanvas();closeSheet()};$('#mFit').onclick=()=>{fitCanvas();closeSheet()};$('#mUndo').onclick=()=>{$('#undoBtn').click();closeSheet()};$('#mRedo').onclick=()=>{$('#redoBtn').click();closeSheet()};$('#mExport').onclick=()=>{closeSheet();openExportModal()};sheetContent.querySelectorAll('[data-board]').forEach(b=>b.onclick=()=>{const d=boardData()[+b.dataset.board];state.boardFilter=d.label==='全图'?null:d;fitCanvas();closeSheet()})}}
function closeSheet(){backdrop.classList.remove('open');sheet.classList.remove('open')}$$('[data-sheet]').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));$('#closeSheet').onclick=closeSheet;backdrop.onclick=closeSheet;
window.addEventListener('resize',()=>{if(state.step===2)drawCrop();if(state.step===3)renderPreview();if(state.step===4&&state.cellPx<=18)fitCanvas()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?$('#redoBtn').click():$('#undoBtn').click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();$('#redoBtn').click()}});
}
